### ISSUE TITLE
ASKnet-Track-II-participant-s-stories-community-Empowerment-2020-2021

### ISSUE THREAD

**Issue by wunbaai** [gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021-#11]
Just want to contribute in the gibert

**Comment by gibertgibs** [comment]
Wumbai.
You are most welcome to participate to this project.All you need to do is fork the repository to your github account and go to where your name is and start to add your story bit by bit using a pull request.

**Comment by wunbaai** [comment]
Thanks

**Comment by gibertgibs** [comment]
Most Welcome buddy
