### ISSUE TITLE
Merging a picture file and a file without a picture.

### ISSUE THREAD

**Issue by gibertgibs** [gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021-#13]
Hey Members,
Have been wondering if there is a possibility of merging two files eg. A photo/picture file to a file with out a picture/MD file.

**Comment by timmwille** [comment]
Name the files you want to merge ;)

**Comment by timmwille** [comment]
[file1](URL) 
https://github.com/gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021/blob/main/Gilbert%20Charles%20%231%20Story.md
[file2](URL)
https://github.com/gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021/blob/main/IMG_20201019_235441_044.jpg

**Comment by gibertgibs** [comment]
Those are the files to be worked on.

**Comment by timmwille** [comment]
haha I meant the URL/Link to that file but I think I get you

**Comment by gibertgibs** [comment]
Okay then fine

**Comment by timmwille** [comment]
https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/blob/main/Gilbert%20Charles%20%231%20Story.md

**Comment by timmwille** [comment]
I added both parts in here and deleted the other file
@gibertgibs

**Comment by gibertgibs** [comment]
Good then thanks alot but how do I do it, I like to do it my self.
