### ISSUE TITLE
remove dashes from start and end of title in repo name

### ISSUE THREAD

**Issue by timmwille** [gibertgibs/-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021-#7]
in "Settings" mark `-ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021-` to `ASKnet-Track-II-participant-s-stories-Community-Empowerment-2020-2021`

**Comment by timmwille** [comment]
technically in the front of the repo name/url/title you still have a dash `-` added :)

**Comment by gibertgibs** [comment]
How do you mean?
